README.md
This commit updates the README to use the index template method
=> Use template method in README

src/Elastic.CommonSchema.Serilog/LogEventConverter.cs
Set `event.severity` to numeric value.
Discussed here: https://github.com/elastic/ecs/issues/683#issuecomment-563248169
=> Use the log event severity if the property is not present.

src/Elastic.Apm.SerilogEnricher/ElasticApmEnricher.cs, src/Elastic.Apm.SerilogEnricher/readme.md, src/Elastic.CommonSchema.Serilog/LogEventConverter.cs, tests/Elastic.Apm.SerilogEnricher.Test/SerilogTests.cs, tests/Elastic.CommonSchema.Serilog.Tests/Elastic.CommonSchema.Serilog.Tests/Elastic.CommonSchema.Serilog.Tests.csproj, tests/Elastic.CommonSchema.Serilog.Tests/Elastic.CommonSchema.Serilog.Tests/EnrichmentsTests.cs
Adds trace and transaction id to the generated logs in `EcsTextFormatter` in case the APM Agent is active.
Configuration:
```
Log.Logger = new LoggerConfiguration()
.Enrich.WithElasticApmCorrelationInfo()
.WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri("http://localhost:9200"))
{
CustomFormatter = new EcsTextFormatter()
})
.CreateLogger();
```
On this screenshot you see the output when I pass `EcsTextFormatter` to the serilog elasticsearch sink.
I ran into 1 problem during testing with ASP.NET Core: It seems that some component uses the property `traceId` (my suspect is [serilog-aspnetcore](https://github.com/serilog/serilog-aspnetcore)), so our trace Id was overwritten by the Activity Id (`Activity.Current.Id`) and broke the navigation between logs and traces in Kibana.
This …
=> Read trace and transaction id from APM in EcsTextFormatter

src/Elastic.Apm.NLog/ApmTraceIdLayoutRenderer.cs, src/Elastic.Apm.NLog/ApmTransactionIdLayoutRenderer.cs, src/Elastic.Apm.NLog/Elastic.Apm.NLog.csproj, src/ecs-dotnet.sln, tests/Elastic.Apm.NLog.Test/Elastic.Apm.NLog.Test.csproj, tests/Elastic.Apm.NLog.Test/NLogTests.cs, tests/Elastic.Apm.SerilogEnricher.Test/SerilogTests.cs, tests/Elastic.Apm.Test.Common/Elastic.Apm.Test.Common.csproj, tests/Elastic.Apm.Test.Common/NoopPayloadSender.cs
From https://github.com/elastic/apm-agent-dotnet/issues/244
Based on this discussion: https://github.com/NLog/NLog/issues/3726 
I gave up on Log4Net for now, details: https://github.com/elastic/apm-agent-dotnet/issues/662  
So, my current plan is that we'll offer APM log correlation integration for NLog and Serilog.
=> Add NLog LayoutRenderer to inject trace and transaction ids into logs

build/scripts/Versioning.fs
Locking assembly identity to minor versions to account for changes in ECS that would break SemVer for the generated classes.
=> Lock versioning to MAJOR.MINOR.0 instead of MAJOR.0.0

src/Elastic.CommonSchema.BenchmarkDotNetExporter/Elastic.CommonSchema.BenchmarkDotNetExporter.csproj
This PR removes the `PrivateAssets="all"` attribute so that the client reference flows to the project.
Fixes #41.
=> Elastic.CommonSchema.BenchmarkDotNetExporter assembly has a private asset reference to the client.

src/Elastic.CommonSchema.Serilog/EcsTextFormatter.cs
=> EcsTextFormatter should write lines to the textwriter to ensure log lines are seperated

.ci/Jenkinsfile, .ci/jobs/defaults.yml, .ci/jobs/ecs-dotnet-mbp.yml, .pre-commit-config.yaml
Enable the JJBB and a CI Pipeline to run:
- checkout
- pre-commit validation
There will be some follow-ups to add more stages to the CI Pipeline. See https://github.com/elastic/ecs-dotnet/pull/49
=> ci(jenkins): enable CI Pipeline and JJBB

.ci/Jenkinsfile, build/scripts/Testing.fs, tests/Elastic.Apm.NLog.Test/Elastic.Apm.NLog.Test.csproj, tests/Elastic.Apm.SerilogEnricher.Test/Elastic.Apm.SerilogEnricher.Test.csproj, tests/Elastic.Apm.Test.Common/Elastic.Apm.Test.Common.csproj, tests/Elastic.CommonSchema.BenchmarkDotNetExporter.IntegrationTests/Elastic.CommonSchema.BenchmarkDotNetExporter.IntegrationTests.csproj, tests/Elastic.CommonSchema.NLog.Tests/Elastic.CommonSchema.NLog.Tests.csproj, tests/Elastic.CommonSchema.Serilog.Tests/Elastic.CommonSchema.Serilog.Tests.csproj, tests/Elastic.CommonSchema.Tests/Elastic.CommonSchema.Tests.csproj
It will run only for the Linux builds for the time being.
As suggested in https://gitlab.com/gitlab-org/gitlab/issues/32869
=> ci(jenkins): enable JUnit output

src/Elastic.Apm.NLog/Elastic.Apm.NLog.csproj, src/Elastic.Apm.SerilogEnricher/Elastic.Apm.SerilogEnricher.csproj, tests/Elastic.Apm.NLog.Test/Elastic.Apm.NLog.Test.csproj, tests/Elastic.Apm.Test.Common/Elastic.Apm.Test.Common.csproj, tests/Elastic.CommonSchema.NLog.Tests/Elastic.CommonSchema.NLog.Tests.csproj, tests/Elastic.CommonSchema.Serilog.Tests/Elastic.CommonSchema.Serilog.Tests.csproj
Solves #61.
With this by default we'll have a version out which contains a fix to https://github.com/elastic/ecs-dotnet/issues/58.
=> Increase Elastic.Apm dependency to 1.4.0

src/Elastic.CommonSchema.NLog/EcsLayout.cs
=> EcsLayout - Use LogEventInfo.Logger instead of hardcoded DefaultLogger

src/Elastic.CommonSchema.NLog/Elastic.CommonSchema.NLog.csproj, src/Elastic.CommonSchema.Serilog/Elastic.CommonSchema.Serilog.csproj, src/Elastic.CommonSchema.Serilog/LogEventConverter.cs
NetCore 2.1 has Long-Term-Support (LTS). Resolves #72
=> Microsoft.AspNetCore.Http.Abstractions ver. 2.1.0 has LTS

src/Elastic.CommonSchema.NLog/EcsLayout.cs
This PR allows for both programmatical and derivational enrichment of NLog ecs events before they are serialized.
Example:
`var tt = new EcsLayout()
{
EnrichAction = (ecsEvent,logEvent) =>
{
if (ecsEvent.Event != null)
ecsEvent.Event.Dataset = "someValue";
}
}`
Or deriving a class from NLog.EcsLayout and overriding the EnrichEvent function.
Both ways are not needed but at least one is. Otherwise a class can't event be derived from [EcsLayout ](https://github.com/elastic/ecs-dotnet/blob/bbc0ff2cd25219e58b2f27956495e2bb8f314277/src/Elastic.CommonSchema.NLog/EcsLayout.cs#L20) and override the [RenderFormattedMessage ](https://github.com/elastic/ecs-dotnet/blob/bbc0ff2cd25219e58b2f27956495e2bb8f314277/src/Elastic.CommonSchema.NLog/EcsLayout.cs#L98) function because all of the called Get* …
=> NLog Ecs Layout event Enrichment

.gitignore, src/ecs-dotnet.sln, tests/Elastic.CommonSchema.Benchmarks/Elastic.CommonSchema.Benchmarks.csproj, tests/Elastic.CommonSchema.Benchmarks/Program.cs, tests/Elastic.CommonSchema.Benchmarks/SerializingBase.cs
Every library needs a BenchmarkDotNet project so this was long overdue.
Looking to get this in so we can set a base line for the changes in #75 cc @snakefoot 
|  Method |         Mean |       Error |      StdDev | Completed Work Items | Lock Contentions |  Gen 0 |  Gen 1 | Gen 2 | Allocated |
|-------- |-------------:|------------:|------------:|---------------------:|-----------------:|-------:|-------:|------:|----------:|
|   Empty |     849.1 ns |     3.22 ns |     2.51 ns |               0.0000 |                - | 0.1135 |      - |     - |     712 B |
| Minimal |   1,441.0 ns |    13.18 ns |    11.69 ns |               0.0000 |                - | 0.1469 |      - |     - |     928 B |
| Complex |   3,913.2 ns |    50.75 ns |    44.99 ns |               0.0000 |                - | …
=> add benchmarks for simple serialization cases

src/Elastic.CommonSchema.NLog/EcsLayout.cs, src/Elastic.CommonSchema.Serilog/LogEventConverter.cs, tests/Elastic.CommonSchema.NLog.Tests/Elastic.CommonSchema.NLog.Tests.csproj, tests/Elastic.CommonSchema.NLog.Tests/LogTestsBase.cs, tests/Elastic.CommonSchema.NLog.Tests/MessageTests.cs
So you can do this:
```xml
<layout type="EcsLayout"
logOriginCallSiteMethod="${callsite}"
logOriginCallSiteFile="${callsite-filename}"
logOriginCallSiteLine="${callsite-linenumber}"
/>
```
See also: https://github.com/NLog/NLog/wiki/Callsite-Layout-Renderer
Trying to fix one item from #77
=> NLog EcsLayout - Added support for Log Origin

src/Elastic.CommonSchema.NLog/EcsLayout.cs, src/Elastic.CommonSchema.NLog/ReusableUtf8JsonWriter.cs, src/Elastic.CommonSchema/Base.Serialization.cs, src/Elastic.CommonSchema/Elastic.CommonSchema.csproj, src/Elastic.CommonSchema/Serialization/EcsSerializerFactory.cs, src/Elastic.CommonSchema/Serialization/ReusableUtf8JsonWriter.cs, tests/Elastic.CommonSchema.Benchmarks/Elastic.CommonSchema.Benchmarks.csproj, tests/Elastic.CommonSchema.Benchmarks/SerializingStringBuilderBase.cs, tests/Elastic.CommonSchema.NLog.Tests/OutputTests.cs
Continuation of #75 
* NLog EcsLayout - Write directly to StringBuilder instead of string allocation
This continuation:
- Move internal ReusableUtf8JsonWriter down to Elastic.CommonSchema
- Expose an overload on `Base` that serializes on a `StringBuilder` directly.
- Add benchmarks for the `StringBuilder` overload
- `ReusableUtf8JsonWriter` is now a `ThreadStatic` instance on `Base`
Reusing the text writer in the `StringBuilder` overload:
|  Method |       Mean |      Error |      StdDev | Completed Work Items | Lock Contentions |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------- |-----------:|-----------:|------------:|---------------------:|-----------------:|-------:|------:|------:|----------:|
|   Empty |   1.064 μs |  0.0047 μs |   0.0042 μs |               0.0000 |                - | …
=> Expose Serialize(StringBuilder) overload

README.md, src/Elastic.Apm.NLog/readme.md, src/Elastic.CommonSchema.NLog/README.md
Generate output to the console-target, instead of in-memory-target.
Make use of the actual EcsLayout, instead of just printing the static string `"EcsLayout"`.
=> Fix documentation for NLog EcsLayout to match Serilog

src/Elasticsearch.Extensions.Logging/ElasticsearchLogger.cs
#95
This PR is a follow up on [this](https://github.com/elastic/ecs-dotnet/pull/85#discussion_r449631514) comment (all the details are in the comment).
=> Remove sending Transaction.Id in Elasticsearch.Extensions.Logging

src/Elasticsearch.Extensions.Logging/ElasticsearchDataProcessor.cs, src/Elasticsearch.Extensions.Logging/ElasticsearchLoggerOptions.cs, src/Elasticsearch.Extensions.Logging/LoggingBuilderExtensions.cs, src/Elasticsearch.Extensions.Logging/ShipTo.cs
This introduces two new extension methods:
- UseElasticCloud(string cloudId, string apiKey)
- UseElasticCloud(string cloudId, string username, string password)
Breaking change:
- Removed NodeUris from the ElasticsearchLoggerOptions
- Added new ShipTo class which encloses the previous NodeUris
I am not 100% sure if this is what you want/need, but it works fine for me.
Tested on a local ElasticSearch instance using `.AddElasticsearch()`.
Tested on elastic cloud using `.AddElasticCloud(cloudId, username, password)`
Tested on elastic cloud using `.AddElasticCloud(cloudId, apiKey)`
The ApiKey has to come in correctly. So the base64'd "ApiKey.Id + colon + ApiKey.Key".
Please let me know if you need anything to be changed.
=> Added ElasticCloud logging

ecs-dotnet.sln, examples/Elasticsearch.Extensions.Logging.Example/Elasticsearch.Extensions.Logging.Example.csproj, examples/Elasticsearch.Extensions.Logging.Example/HighVolumeWorkSimulation.cs, examples/Elasticsearch.Extensions.Logging.Example/Log.cs, examples/Elasticsearch.Extensions.Logging.Example/LowVolumeWorkSimulation.cs, examples/Elasticsearch.Extensions.Logging.Example/Program.cs, examples/Elasticsearch.Extensions.Logging.Example/Worker.cs, examples/Elasticsearch.Extensions.Logging.Example/appsettings.json, src/Elasticsearch.Extensions.Logging/ConsumerBuffer.cs, src/Elasticsearch.Extensions.Logging/Elasticsearch.Extensions.Logging.csproj, src/Elasticsearch.Extensions.Logging/ElasticsearchDataShipper.cs, src/Elasticsearch.Extensions.Logging/ElasticsearchLogger.cs, src/Elasticsearch.Extensions.Logging/ElasticsearchLoggerOptions.cs, src/Elasticsearch.Extensions.Logging/ElasticsearchLoggerProvider.cs, tests/Elasticsearch.Extensions.Logging.IntegrationTests/LoggingTests.cs
Continuation of #97
Introduces batching of log events before indexing into Elasticsearch. Powered by `System.Threading.Channels`. It supports sending every N items or every M interval after the first item was added. 
This also introduces the ability to have multiple consumers drain the channel concurrently. 
A callback now exists when items are being dropped because the channel is full and when a `_bulk` request has occurred. 
We still need to add 
- _bulk failure handling
- _bulk retry handling (exponential backoff)
- _bulk rejection callback for `LogEvent` 
Since this PR and #97 are big enough already will tackle the remained when we pull in the flight PR's. 
This also includes a modified version of the example project from @sgryphon 's PR: #69 
It also includes a high volume worker …
=> Bulk support for extensions logging integration.

ecs-dotnet.sln, examples/Elasticsearch.Extensions.Logging.Example/Program.cs, src/Elastic.Ingest/BufferOptions.cs, src/Elastic.Ingest/ChannelBuffer.cs, src/Elastic.Ingest/ConnectionPoolType.cs, src/Elastic.Ingest/Elastic.Ingest.csproj, src/Elastic.Ingest/ElasticsearchChannel.cs, src/Elastic.Ingest/ElasticsearchChannelOptions.cs, src/Elastic.Ingest/ElasticsearchLoggerOptions.cs, src/Elastic.Ingest/ShipTo.cs, src/Elasticsearch.Extensions.Logging/Elasticsearch.Extensions.Logging.csproj, src/Elasticsearch.Extensions.Logging/ElasticsearchLogger.cs, src/Elasticsearch.Extensions.Logging/ElasticsearchLoggerOptions.cs, src/Elasticsearch.Extensions.Logging/ElasticsearchLoggerProvider.cs, src/Elasticsearch.Extensions.Logging/LoggingBuilderExtensions.cs, tests/Elasticsearch.Extensions.Logging.IntegrationTests/LoggingTests.cs
This moves the shipping component from `Elasticsearch.Extensions.Logging` into its own package.
This allows any application to new an `ElasticsearchChannel<TEvent>` and
use it to push data into through  `TryWrite()` . The channel will then take care of
buffering and retrying etc.
=> Move actual shipper into own project

src/Elasticsearch.Extensions.Logging/Elasticsearch.Extensions.Logging.csproj
As per the GA plan, use lower level package for wider usability.
=> Downgrade Microsoft.Extensions.* packages to 2.1.0.

src/Elastic.CommonSchema.Serilog/LogEventConverter.cs
Writing hostname to the IP field creates logs like the one below:
{"@timestamp":"2020-10-21T14:02:51.7698395+03:00","log.level":"Information","message":"Request starting HTTP/1.1 GET http://10.132.4.163:5111/readiness ","_metadata":{"message_template":"{HostingRequestStartingLog:l}","protocol":"HTTP/1.1","method":"GET","content_type":null,"content_length":null,"scheme":"http","path_base":"","path":"/readiness","query_string":"","hosting_request_starting_log":"Request starting HTTP/1.1 GET http://10.132.4.163:5111/readiness ","event_id":{"id":1},"request_id":"0HM3LHKKTLRML:00000001","request_path":"/readiness","span_id":"|3d1c3928-4b1f17b80024b28b.","trace_id":"3d1c3928-4b1f17b80024b28b","parent_id":"","connection_id":"0HM3LHKKTLRML"},"ecs":{"version":"1.5.0"},"event":{"severity":2,"timezon …
=> fix #87 hostname shouldn't be written in server.IP field

src/Elastic.Apm.NLog/Elastic.Apm.NLog.csproj, src/Elastic.CommonSchema.NLog/EcsLayout.cs, src/Elastic.CommonSchema.NLog/README.md, src/Elastic.CommonSchema.Serilog/LogEventConverter.cs
=> Fixed Exception StackTrace formatting to handle missing StackFrames

docs/index.asciidoc, docs/intro.asciidoc, docs/setup.asciidoc, docs/tab-widgets/add-dependency-widget.asciidoc, docs/tab-widgets/add-dependency.asciidoc, docs/tab-widgets/code.asciidoc, docs/tab-widgets/ecs-integration-widget.asciidoc, docs/tab-widgets/ecs-integration.asciidoc
Relates: #119
This commit adds initial documentation for the elastic.co website. It follows a similar layout and structure to the ECS logging documentation for Java.
=> Initial documentation for elastic.co

.gitignore, docs/index.asciidoc, docs/intro.asciidoc, docs/setup.asciidoc, docs/tab-widgets/ecs-integration.asciidoc
This PR updates the `ecs-dotnet` docs to use shared content from the `ecs-logging` docs. It also fixes some asciidoc errors in `ecs-integration.asciidoc` that were preventing the docs from building.
To test this PR, you'll need an up-to-date copy of both [`elastic/docs`](https://github.com/elastic/docs) and [`elastic/ecs-logging`](https://github.com/elastic/ecs-logging). Then run:
```
$GIT_HOME/docs/build_docs --doc $GIT_HOME/ecs-dotnet/docs/index.asciidoc --resource=$GIT_HOME/ecs-logging/docs/ --chunk 1 --open
```
For https://github.com/elastic/docs/pull/2018.
=> docs: Use shared ecs-logging content

tests/Elastic.CommonSchema.Tests/Specs/spec.json
ECS logging specs automatic sync
*Manually forced with the CI automation job.*
=> test: synchronizing spec

.ci/docker/sdk-linux/Dockerfile
This `5.0.102-ca-patch-buster-slim` tag is no longer needed and is no longer serviced.
Context: https://github.com/dotnet/dotnet-docker/issues/2742
As an aside, do you have any feedback on how .NET container images can be improved? Do they meet your expectations?
=> Switch to serviced dotnet/sdk tag

src/Elastic.CommonSchema.NLog/EcsLayout.cs, src/Elastic.CommonSchema/Serialization/BaseJsonFormatter.Generated.cs, src/Elastic.CommonSchema/Types.Generated.cs, src/Elastic.CommonSchemaNEST/TypeMappings.Generated.cs, src/Elasticsearch.Extensions.Logging/ElasticsearchLogger.cs, src/Generator/SchemaExtensionMethods.cs, src/Generator/Views/Types.Generated.cshtml, tests/Elastic.CommonSchema.NLog.Tests/LogTestsBase.cs, tests/Elastic.CommonSchema.NLog.Tests/MessageTests.cs
=> fix #68 labels should be dict of string to string

docs/setup.asciidoc, src/Elastic.Apm.NLog/ApmSpanIdLayoutRenderer.cs, src/Elastic.Apm.NLog/ApmTraceIdLayoutRenderer.cs, src/Elastic.Apm.NLog/ApmTransactionIdLayoutRenderer.cs, src/Elastic.Apm.NLog/readme.md, src/Elastic.Apm.SerilogEnricher/ElasticApmEnricher.cs, src/Elastic.Apm.SerilogEnricher/readme.md, src/Elastic.CommonSchema.NLog/EcsLayout.cs, src/Elastic.CommonSchema.Serilog/LogEventConverter.cs, tests/Elastic.Apm.NLog.Test/NLogTests.cs, tests/Elastic.Apm.SerilogEnricher.Test/SerilogTests.cs, tests/Elastic.CommonSchema.NLog.Tests/ApmTests.cs, tests/Elastic.CommonSchema.NLog.Tests/LogTestsBase.cs, tests/Elastic.CommonSchema.Serilog.Tests/EnrichmentsTests.cs
With the introduction of span id into ECS schema 1.6, this commit adds the span id to APM logging integrations when there is an active span.
=> Add span id to APM Logging integrations

src/Elastic.Ingest/ChannelBuffer.cs, src/Elastic.Ingest/Elastic.Ingest.csproj, src/Elastic.Ingest/ElasticsearchChannel.cs, src/Elastic.Ingest/Serialization/Model.cs, src/Elastic.Ingest/ShipTo.cs, src/Elasticsearch.Extensions.Logging/ElasticsearchLogger.cs, src/Elasticsearch.Extensions.Logging/ElasticsearchLoggerOptions.cs, src/Elasticsearch.Extensions.Logging/ElasticsearchLoggerProvider.cs, src/Elasticsearch.Extensions.Logging/LogEventToEcsHelper.cs, tests/Elastic.Ingest.Tests/SerializationTests.cs
This PR refactors Elasticsearch.Extensions.Logging in preparation for an initial release
- Remove caching loggers in a concurrent dictionary in `ElasticsearchLoggerProvider`
Can evaluate later if the performance improvements in doing this would justify the added complexity. Most notably, there is no mechanism to remove loggers from the dictionary, which for an unknown logger naming convention, could allow it to grow unbounded.
- Move `ElasticsearchLogger` required properties into the ctor
- Fix bulk item response serialization
- Add package details to Elastic.Ingest
=> Refactor Elasticsearch.Extensions.Logging

src/Elastic.CommonSchema.BenchmarkDotNetExporter/Domain/BenchmarkGcStats.cs, src/Elastic.CommonSchema.BenchmarkDotNetExporter/Elastic.CommonSchema.BenchmarkDotNetExporter.csproj, src/Elastic.CommonSchema.BenchmarkDotNetExporter/ElasticsearchBenchmarkExporter.cs, tests/Elastic.CommonSchema.BenchmarkDotNetExporter.IntegrationTests/Elastic.CommonSchema.BenchmarkDotNetExporter.IntegrationTests.csproj, tests/Elastic.CommonSchema.Benchmarks/Elastic.CommonSchema.Benchmarks.csproj, tests/Elasticsearch.Extensions.Logging.IntegrationTests/Elasticsearch.Extensions.Logging.IntegrationTests.csproj
Needed a newer version of BenchmarkDotNet and also needed to be able to configure the elasticsearch client more than what ElasticsearchBenchmarkExporterOptions allows.
=> Update BenchmarkDotNet and allow more client configuration

src/Elastic.CommonSchema.NLog/EcsLayout.cs, src/Elastic.CommonSchema.NLog/README.md, tests/Elastic.CommonSchema.NLog.Tests/LogTestsBase.cs
Align with [NLog 5.0](https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html) where `IncludeAllProperties` is confusing, since there is both IncludeEventProperties and IncludeScopeProperties
=> NLog EcsLayout now recognizes IncludeEventProperties and IncludeScopeProperties

src/Elastic.CommonSchema.BenchmarkDotNetExporter/Domain/BenchmarkConfidence.cs, src/Elastic.CommonSchema.BenchmarkDotNetExporter/Domain/BenchmarkDocument.cs, src/Elastic.CommonSchema.BenchmarkDotNetExporter/Domain/BenchmarkEvent.cs, src/Elastic.CommonSchema.BenchmarkDotNetExporter/Domain/BenchmarkGcInfo.cs, src/Elastic.CommonSchema.BenchmarkDotNetExporter/Domain/BenchmarkGcStats.cs, src/Elastic.CommonSchema.BenchmarkDotNetExporter/Domain/BenchmarkGit.cs, src/Elastic.CommonSchema.BenchmarkDotNetExporter/Domain/BenchmarkHost.cs, src/Elastic.CommonSchema.BenchmarkDotNetExporter/Domain/BenchmarkJobConfig.cs, src/Elastic.CommonSchema.BenchmarkDotNetExporter/Domain/BenchmarkLanguage.cs, src/Elastic.CommonSchema.BenchmarkDotNetExporter/Domain/BenchmarkLaunchInformation.cs, src/Elastic.CommonSchema.BenchmarkDotNetExporter/Domain/BenchmarkMeasurementStage.cs, src/Elastic.CommonSchema.BenchmarkDotNetExporter/Domain/BenchmarkSimplifiedWorkloadCounts.cs, src/Elastic.CommonSchema.BenchmarkDotNetExporter/Domain/Domain.cs, src/Elastic.CommonSchema.Generator/Views/EcsDocument.Generated.cshtml, src/Elastic.CommonSchema.Generator/Views/Entities.Generated.cshtml, src/Elastic.CommonSchema.Generator/Views/FieldSets.Generated.cshtml, src/Elastic.CommonSchema.Generator/Views/IndexComponents.Generated.cshtml, src/Elastic.CommonSchema.Generator/Views/IndexTemplates.Generated.cshtml, src/Elastic.CommonSchema.Generator/Views/InlineObjects.Generated.cshtml, src/Elastic.CommonSchema/EcsDocument.Generated.cs, src/Elastic.CommonSchema/Entities.Generated.cs, src/Elastic.CommonSchema/FieldSets.Generated.cs, src/Elastic.CommonSchema/IndexComponents.Generated.cs, src/Elastic.CommonSchema/IndexTemplates.Generated.cs, src/Elastic.CommonSchema/InlineObjects.Generated.cs, src/Elastic.CommonSchema/Location.cs, src/Elastic.CommonSchema/README.md, src/Elasticsearch.Extensions.Logging/LogEvent.cs, tests/Elastic.CommonSchema.Tests/Serializes.cs
- Move to JsonPropertyName
- Run code generation, moving to JsonPropertyName
- add more tests to ensure nested properties are written using declared names.
Update: Both `JsonPropertyName` and `DataMember()` need to be present to ensure compatibility with Json.NET and UTF8 json. This ensures the Elasticsearch Client up to version 7 can still read EcsDocument out of the box. We had integration tests checking deeply nested properties using the v7 Elasticsearch client.
cc @andreycha
=> Fix #205 Use both DataMember and JsonPropertyName attributes on ECS types

src/Elastic.Apm.NLog/ApmServiceNameLayoutRenderer.cs, src/Elastic.Apm.NLog/ApmServiceNodeNameLayoutRenderer.cs, src/Elastic.Apm.NLog/ApmServiceVersionLayoutRenderer.cs, src/Elastic.Apm.NLog/readme.md, src/Elastic.Apm.SerilogEnricher/ElasticApmEnricher.cs, src/Elastic.CommonSchema.NLog/EcsLayout.cs, src/Elastic.CommonSchema.Serilog/LogEventConverter.cs, tests/Elastic.Apm.NLog.Test/NLogTests.cs, tests/Elastic.Apm.SerilogEnricher.Test/ServiceInformationTests.cs, tests/Elastic.Apm.SerilogEnricher.Test/TraceInformationTests.cs, tests/Elastic.Apm.Test.Common/MockConfiguration.cs, tests/Elastic.Apm.Test.Common/TestApmAgent.cs, tests/Elastic.CommonSchema.NLog.Tests/ApmTests.cs, tests/Elastic.CommonSchema.NLog.Tests/Elastic.CommonSchema.NLog.Tests.csproj, tests/Elastic.CommonSchema.NLog.Tests/LogTestsBase.cs, tests/Elastic.CommonSchema.Serilog.Tests/Elastic.CommonSchema.Serilog.Tests.csproj, tests/Elastic.CommonSchema.Serilog.Tests/EnrichmentsTests.cs
- Expose service information to serilog and expose it to EcsTextJsonFormatter
- Expose service information to NLog and ensure Elastic.CommonSchema.NLog sets Service information
Fixes: #134
=> Ensure APM service name gets exposed to Serilog/NLog ECS export"

src/Elastic.CommonSchema.Generator/Projection/TypeProjector.cs, src/Elastic.CommonSchema.Generator/Views/EcsDocument.Generated.cshtml, src/Elastic.CommonSchema/EcsDocument.Generated.cs, tests/Elasticsearch.Extensions.Logging.IntegrationTests/LoggingToDataStreamTests.cs
And not the gitref that we used to generate the types from
Fixes #216
=> Ensure ECS version is the schema version

examples/aspnetcore-with-serilog/Program.cs, src/Elastic.CommonSchema.Serilog/EcsTextFormatter.cs, src/Elastic.CommonSchema.Serilog/EcsTextFormatterConfiguration.cs, src/Elastic.CommonSchema.Serilog/LogEventConverter.cs, tests/Elastic.CommonSchema.Serilog.Tests/LogEventPropFilterTests.cs, tests/Elastic.CommonSchema.Serilog.Tests/Repro/GithubIssue167.cs
This way users can implement and use their own EcsDocument subclasses as `ITextFormatter`.
This introduces some breaking changes:
- `EcsTextFormatterConfiguration` is no longer a fluent descriptor, just a simple POCO.
- The MapFromContext() helper method no longer exists.
Fixes #167
=> Allow EcsTextFormatter to accept any custom EcsDocument implementation

src/Elastic.CommonSchema/Serialization/JsonConfiguration.cs, src/Elastic.CommonSchema/Serialization/MetadataDictionaryConverter.cs, tests/Elastic.CommonSchema.NLog.Tests/ApmTests.cs, tests/Elastic.CommonSchema.NLog.Tests/EcsFieldsInTemplateTests.cs, tests/Elastic.CommonSchema.NLog.Tests/LogTestsBase.cs, tests/Elastic.CommonSchema.NLog.Tests/MessageTests.cs, tests/Elastic.CommonSchema.NLog.Tests/OutputTests.cs
=> EcsJsonConfiguration - With converters to protect against bad types

src/Elastic.CommonSchema.Generator/CodeConfiguration.cs, src/Elastic.CommonSchema.Generator/FileGenerator.cs, src/Elastic.CommonSchema.Generator/Projection/ProjectionTypeExtensions.cs, src/Elastic.CommonSchema.Generator/Projection/PropertyReference.cs, src/Elastic.CommonSchema.Generator/Projection/TypeProjector.cs, src/Elastic.CommonSchema.Generator/Views/EcsDocumentJsonConverter.Generated.cshtml, src/Elastic.CommonSchema.Generator/Views/EcsJsonContext.Generated.cshtml, src/Elastic.CommonSchema.Generator/Views/EcsLogJsonConverter.Generated.cshtml, src/Elastic.CommonSchema/Entities.cs, src/Elastic.CommonSchema/Serialization/EcsDocumentJsonConverter.Generated.cs, src/Elastic.CommonSchema/Serialization/EcsDocumentJsonConverter.cs, src/Elastic.CommonSchema/Serialization/EcsJsonContext.Generated.cs, src/Elastic.CommonSchema/Serialization/EcsJsonConverterBase.cs, src/Elastic.CommonSchema/Serialization/EcsLogJsonConverter.Generated.cs, src/Elastic.CommonSchema/Serialization/EcsLogJsonConverter.cs, src/Elastic.CommonSchema/Serialization/JsonConfiguration.cs, tests/Elastic.CommonSchema.Tests/LogLevelTests.cs
With the new serialization generation we were emitting log level twice
once under `log.level` and once as `log: { level: }`
This PR addresses this to ensure we never emit the latter but are able
to read both versions of the json.
This to make sure the JSON we emit is compatible with the
`json.expand_keys` option in filebeat as identified as @elan-slovelock
This PR also makes sure we never emit `log: {}` if only log level is
set.
=> Fixes #86 only write log level once

tests/Elastic.CommonSchema.Tests/Specs/spec.json
ECS logging specs automatic sync
*Changeset*
* https://github.com/elastic/ecs-logging/commit/438fc2c Ensure ecs.version is treated as a top level field (https://github.com/elastic/ecs-logging/pull/71)
=> synchronize ecs-logging spec

.github/workflows/test-reporter.yml
These do not appear to preserve directories inside the zip:
```
Report name: JUnit Tests
Skipping junit-Elastic.Apm.Disabled.Serilog.Tests-NETCoreApp60-test-results.xml: filename does not match pattern
Skipping junit-Elastic.Apm.NLog.Test-NETCoreApp60-test-results.xml: filename does not match pattern
Skipping junit-Elastic.Apm.SerilogEnricher.Test-NETCoreApp60-test-results.xml: filename does not match pattern
Skipping junit-Elastic.CommonSchema.BenchmarkDotNetExporter.IntegrationTests-NETCoreApp60-test-results.xml: filename does not match pattern
Skipping junit-Elastic.CommonSchema.Log4net.Tests-NETCoreApp60-test-results.xml: filename does not match pattern
Skipping junit-Elastic.CommonSchema.NLog.Tests-NETCoreApp60-test-results.xml: filename does not match pattern
Skipping …
```
=> make sure we read the junit files in the zip

examples/Elastic.CommonSchema.Serilog.Sink.Example/Program.cs, src/Elastic.CommonSchema.Serilog.Sink/ElasticsearchSink.cs, src/Elastic.CommonSchema.Serilog.Sink/ElasticsearchSinkExtensions.cs
This allows you to use the Serilog Sink with your own EcsDocument
subclasses
=> Add generic config options to LoggerSinkConfiguration

src/Elastic.CommonSchema/Serialization/EcsDocumentJsonConverter.cs, tests/Elastic.CommonSchema.Tests/Deserializes.cs
Similar fix as #187 but with failing (now fixed) unit tests
=> Fix #182 Ensure EcsDocumentJsonConverter reads to completion

src/Elastic.Apm.NLog/Elastic.Apm.NLog.csproj, src/Elastic.CommonSchema.NLog/Elastic.CommonSchema.NLog.csproj, tests/Elastic.Apm.NLog.Tests/Elastic.Apm.NLog.Tests.csproj, tests/Elastic.CommonSchema.NLog.Tests/Elastic.CommonSchema.NLog.Tests.csproj
NLog v4.7.15 has no breaking changes (remains strong-version 4.0.0.0), and lots of improvements and bug-fixes.
Ensures `${hostname}` and `${local-ip}` and `${environment-user}` works as expected in EcsLayout (improve out-of-the-box experience)
=> Elastic.Apm.NLog + Elastic.CommonSchema.Nlog with NLog v4.7.15

src/Elastic.CommonSchema.Log4net/LoggingEventConverter.cs, src/Elastic.CommonSchema.NLog/EcsLayout.cs, src/Elastic.CommonSchema.Serilog/EcsTextFormatterConfiguration.cs, src/Elastic.CommonSchema.Serilog/Http/IHttpAdapter.cs, src/Elastic.CommonSchema.Serilog/LogEventConverter.cs, src/Elastic.CommonSchema/EcsDocument.cs, src/Elastic.CommonSchema/Elastic.CommonSchema.csproj, src/Elasticsearch.Extensions.Logging/ElasticsearchLogger.cs, src/Elasticsearch.Extensions.Logging/LogEventToEcsHelper.cs, src/Elasticsearch.Extensions.Logging/Options/ElasticsearchLoggerOptions.cs, tests/Elastic.CommonSchema.Log4net.Tests/MessageTests.cs
All integrations now create a new `EcsDocument` (or subclass) instance through:
```csharp
var ecs = EcsDocument.CreateNewWithDefaults<EcsDocument>(log.TimeStamp, log.Exception);
```
This ensures a default common minimum is achieved across all logging integrations:
- `ecs.version` is set and cached.
- tracing information is applied if available on `Activity.Current` this also addresses:
- #152 
- #169 
- #210
- `process.*` is set and cached
- `service.*` is set and cached
- `user.*` is set
- A helper also is added to ensure `agent.*` is set using the same assembly version resolvment logic as `service.*`
- Exceptions are now all translated to `error.*` in the same way.
=> Fix #55 Centralize EcsDocument creation with defaults

.github/workflows/opentelemetry.yml, .github/workflows/update-specs.yml
Use GitHub composite action
Reuse code and solve the existing issue with Workflows won't be enabled for PRs created on behalf of `GitHub actions [bot]`, see https://github.com/elastic/ecs-logging-java/pull/200
Similar to https://github.com/elastic/ecs-logging-java/pull/201
Requires https://github.com/elastic/apm-pipeline-library/pull/2076
=> action: use composite updatecli and monitor more workflows

.github/workflows/release-main.yml
Sadly GH package repos still does not support anonymous access so we can't replace feedz.io with it yet. Feedz.io has also served us amazingly well for a long time so not in any rush replacing it. 
This additional push does help advertise which nuget packages this repository builds e.g:
From https://github.com/elastic/elastic-ingest-dotnet which already pushes to GH package repository.
=> Release to github package repository as well

src/Elastic.CommonSchema/EcsDocument.cs
The **EcsTextFormatter** performs really slowly with the File sink in Serilog.
On my lower-end virtual machine, I performed the test cases below: I initialized Serilog with a simple configuration to sink logs in a file with different formatters:
1. CompactJsonFormatter
2. EcsTextFormatter
The CompactJsonFormatter took an average of **0.45 seconds** to write 12,000 log messages, while the EcsTextFormatter took **5.5 seconds**.
Surprisingly, through profiling, I found that _Environment.UserName_ and _Environment.UserDomainName_ were the hottest path in execution.
So I **cached those variables in a static field** and performed the same case, which brought down the time to **1 second**.
Overall, there will be a significant improvement in throughput.
=> Cache UserName and Domain to improve performance when creating new EcsDocument

examples/Elastic.CommonSchema.Serilog.Sink.Example/Program.cs, src/Elastic.CommonSchema.BenchmarkDotNetExporter/ElasticsearchBenchmarkExporter.cs, src/Elastic.CommonSchema.BenchmarkDotNetExporter/ElasticsearchBenchmarkExporterOptions.cs, src/Elastic.CommonSchema.Serilog.Sink/ElasticsearchSink.cs, src/Elastic.Ingest.Elasticsearch.CommonSchema/EcsDataStreamChannel.cs, src/Elastic.Ingest.Elasticsearch.CommonSchema/Elastic.Ingest.Elasticsearch.CommonSchema.csproj, src/Elasticsearch.Extensions.Logging/ElasticsearchLogger.cs, src/Elasticsearch.Extensions.Logging/ElasticsearchLoggerProvider.cs, tests-integration/Elastic.CommonSchema.BenchmarkDotNetExporter.IntegrationTests/BdNetExporterTests.cs, tests-integration/Elastic.CommonSchema.Serilog.Sink.IntegrationTests/Elastic.CommonSchema.Serilog.Sinks.IntegrationTests.csproj, tests-integration/Elastic.CommonSchema.Serilog.Sink.IntegrationTests/SerilogCluster.cs, tests-integration/Elastic.CommonSchema.Serilog.Sink.IntegrationTests/SerilogSelfLogTests.cs, tests-integration/Elastic.CommonSchema.Serilog.Sink.IntegrationTests/SerilogTestBase.cs, tests-integration/Elastic.Ingest.Elasticsearch.CommonSchema.IntegrationTests/DataStreamIngestionTests.cs, tests-integration/Elastic.Ingest.Elasticsearch.CommonSchema.IntegrationTests/IndexIngestionTests.cs, tests-integration/Elasticsearch.Extensions.Logging.IntegrationTests/LoggingToDataStreamTests.cs, tests-integration/Elasticsearch.Extensions.Logging.IntegrationTests/LoggingToIndexTests.cs, tests-integration/Elasticsearch.Extensions.Logging.IntegrationTests/TestBase.cs, tests-integration/Elasticsearch.IntegrationDefaults/Elasticsearch.IntegrationDefaults.csproj, tests-integration/Elasticsearch.IntegrationDefaults/IngestionCluster.cs
Elastic.Ingest now models the callbacks more rigourously allowing
implementations to inject their own into the channel without overriding
anything the channel itself might rely on or the user might override in
their channeloptions.
This allows e.g the serilog implementation to inject its own listeners
in isolation to log to SelfLog in isolation
=> Update to latest Elastic.Ingest so we can more reliably log to selflog

examples/Elastic.CommonSchema.Serilog.Sink.Example/Elastic.CommonSchema.Serilog.Sink.Example.csproj, examples/Elastic.CommonSchema.Serilog.Sink.Example/Program.cs, examples/aspnetcore-with-serilog/AspnetCoreExample.csproj, examples/aspnetcore-with-serilog/Program.cs, examples/aspnetcore-with-serilog/Startup.cs, src/Elastic.Apm.NLog/Elastic.Apm.NLog.csproj, src/Elastic.Apm.SerilogEnricher/Elastic.Apm.SerilogEnricher.csproj, tests/Elastic.Apm.NLog.Tests/Elastic.Apm.NLog.Tests.csproj, tests/Elastic.Apm.Test.Common/Elastic.Apm.Test.Common.csproj, tests/Elastic.Apm.Test.Common/MockConfiguration.cs, tests/Elastic.CommonSchema.NLog.Tests/Elastic.CommonSchema.NLog.Tests.csproj, tests/Elastic.CommonSchema.Serilog.Tests/Elastic.CommonSchema.Serilog.Tests.csproj
- Fix #292 bump apm to version that eagerly reads configuration
- Ensure our examples are using the APM corrolation providers
=> Bump minimum Elastic.APM to version that eagerly reads configuration

src/Elastic.CommonSchema.Serilog/Adapters/HttpContextAccessorAdapter.cs, src/Elastic.CommonSchema.Serilog/Adapters/HttpContextAdapter.cs, src/Elastic.CommonSchema.Serilog/Adapters/IHttpAdapter.cs, src/Elastic.CommonSchema.Serilog/EcsTextFormatter.cs, src/Elastic.CommonSchema.Serilog/EcsTextFormatterConfiguration.cs, src/Elastic.CommonSchema.Serilog/Elastic.CommonSchema.Serilog.csproj, src/Elastic.CommonSchema.Serilog/HttpContextEnricher.cs, src/Elastic.CommonSchema.Serilog/Lib/UAParser.cs, src/Elastic.CommonSchema.Serilog/LogEventConverter.cs, src/Elastic.CommonSchema.Serilog/ScalarPropertyExtensions.cs, tests/Elastic.CommonSchema.Log4net.Tests/MessageTests.cs, tests/Elastic.CommonSchema.Serilog.Tests/EnrichmentsTests.cs, tests/Elastic.CommonSchema.Serilog.Tests/MessageTests.cs
Introduce `TryGetScalarString` as extention to `TryGetScalarPropertyValue` that does not assume `ScalarProperty.Value` is never null if returned. 
Further more this enables stricter null checks.
=> Add nullable support to Elastic.CommonSchema.Serilog

ecs-dotnet.sln, src/Elastic.CommonSchema.Serilog/Elastic.CommonSchema.Serilog.csproj, src/Elastic.Extensions.Logging/Elastic.Extensions.Logging.csproj, src/Elastic.Extensions.Logging/ElasticsearchLoggerProvider.cs, src/Elastic.Extensions.Logging/Options/ShipToOptions.cs, src/NullableExtensions.cs
Previously this was only applied to Cloud connections
=> Ensure Elastic.Extensions.Logging can set auth through config

src/Elastic.CommonSchema/Serialization/EcsJsonConverterBase.cs, src/Elastic.CommonSchema/Serialization/MetadataDictionaryConverter.cs, src/Elastic.CommonSchema/Serialization/PropertiesReaderJsonConverterBase.Generated.cs, src/Elastic.CommonSchema/Serialization/PropertiesReaderJsonConverterBase.cs, tests/Elastic.CommonSchema.Tests/EcsServiceTests.cs, tests/Elastic.CommonSchema.Tests/Repro/GithubIssue316.cs, tools/Elastic.CommonSchema.Generator/Views/PropertiesReaderJsonConverterBase.Generated.cshtml
Ensures we don't fail on deserialising: 
```json
"log": {
"logger":"root",
"origin": {
"file": {"line":90,"name":"main.py"},
"function":"prepare_logging"
}
}
```
Technically the ecs-json should be in the following format:
```json
"log":{
"logger":"root",
"origin.file.line":90,
"origin.file.name":"main.py"
"origin.function":"prepare_logging"
}
```
This is also the format that beats will emit see e.g: https://github.com/elastic/beats/blob/e9272adcfcdd674b7a787ddd3a2416ad6f2c12be/libbeat/ecs/log.go#L48
Since this might be common enough this PR also adds support for deserializing the expanded form of `log`.
=> ensure log jsonconverter can handle extra properties

src/Elastic.CommonSchema.NLog/EcsLayout.cs, tests/Elastic.CommonSchema.NLog.Tests/Elastic.CommonSchema.NLog.Tests.csproj, tests/Elastic.CommonSchema.NLog.Tests/LogTestsBase.cs, tests/Elastic.CommonSchema.NLog.Tests/WebTests.cs
Resolves issue #296, by introducing IncludeAspNetProperties property to allow consumers to disable AspNet fields rendering. Extend support of AspNet fields rendering to NLog 4.7 (not only 5.0). AspNet related properties in EcsLayout class are not initialized in constructor as before, but in Initialize method.
=> IncludeAspNetProperties property

src/Elastic.Serilog.Sinks/ElasticsearchSink.cs, src/Elastic.Serilog.Sinks/ElasticsearchSinkExtensions.cs
This allows the sink to have a separate logging level from other sinks.
Either hardcoded through restrictedToMinimumLevel (name by convention)
Or dynamically through `LoggingLevelSwitch`
Fixes #309, #310
=> Support LoggingLevelSwitch and restrictedToMinimumLevel in Serilog Sink

examples/aspnetcore-with-serilog/README.md
Update readme in ASP.NET Core with Serilog example. E.g., `MapHttpContext()` does not exist anymore.
=> Update readme in ASP.NET Core with Serilog example

src/Elastic.CommonSchema.Log4net/Elastic.CommonSchema.Log4net.csproj, src/Elastic.CommonSchema.Log4net/LoggingEventConverter.cs, src/Elastic.CommonSchema.Log4net/README.md, tests/Elastic.CommonSchema.Log4net.Tests/EcsFieldsAsPropertiesTests.cs, tests/Elastic.CommonSchema.Log4net.Tests/LogTestsBase.cs, tests/Elastic.CommonSchema.Log4net.Tests/MessageTests.cs
**Motivation**
If a property is added to the log scope multiple times, currently all its values are logged in metadata/labels. This is how log4net also behaves but in most of the cases it is undesired behavior. Only latest property value should be included (e.g., Serilog behaves the same way).
Example:
```cs
using (LogicalThreadContext.Stacks["Id"].Push("123"))
{
log.Info("Log 1"); // currently has "123" in the log metadata
using (LogicalThreadContext.Stacks["Id"].Push("456"))
{
log.Info("Log 2"); // currently has "123 456" in the log metadata; should have "456" instead
using (LogicalThreadContext.Stacks["Id"].Push("789"))
{
log.Info("Log 3"); // currently has "123 456 789" in the log metadata; should have "789" instead
}
}
}
```
**Breaking change:** yes (comparing to how log4net behaves …
=> log4net layout: log latest scope value

src/Elastic.CommonSchema.NLog/EcsLayout.cs, src/Elastic.CommonSchema.NLog/README.md, src/Elastic.CommonSchema.Serilog/LogEventConverter.cs, src/Elastic.CommonSchema.Serilog/README.md, tests/Elastic.CommonSchema.NLog.Tests/MessageTests.cs
"Original"-field was removed from "Log"-section with #194 . Now trying to restore it as "MessageTemplate" property.
Curious where the recommended place to put the original "MesageTemplate". See also: https://discuss.elastic.co/t/log-original-field-lost-with-upgrade-8-6-1-from-1-5-3/348363
Have tried to follow the Elastic Extensions logging, so "MesageTemplate" becomes additional property. See also: https://www.elastic.co/guide/en/ecs-logging/dotnet/current/extensions-logging-data-shipper.html#_example_document
=> NLog EcsLayout - Added support for ProcessThreadName + MessageTemplate

src/Elastic.CommonSchema/EcsDocument.DefaultService.cs, src/Elastic.CommonSchema/EcsDocument.cs, src/Elastic.CommonSchema/Elastic.CommonSchema.csproj, src/Elastic.CommonSchema/Location.cs, src/Elastic.CommonSchema/Serialization/EcsDocumentJsonConverterFactory.cs
This adds dotnet 6 as a TFM so that explicit dependencies can be reduced by using framework provided implementations.
closes #357
=> #357 add in dotnet 6 TFM and tweak dependencies

ecs-dotnet.sln, examples/playground/Program.cs, examples/playground/playground.csproj, src/Elastic.Ingest.Elasticsearch.CommonSchema/Elastic.Ingest.Elasticsearch.CommonSchema.csproj, tests-integration/Elasticsearch.IntegrationDefaults/Elasticsearch.IntegrationDefaults.csproj
This brings in the latest improvements from https://github.com/elastic/elastic-ingest-dotnet
https://github.com/elastic/elastic-ingest-dotnet/pull/53
https://github.com/elastic/elastic-ingest-dotnet/pull/52
Ensure we act way nicer when logging in a very tight loop. 
This fixes #341 
As noted on: https://github.com/elastic/elastic-ingest-dotnet/pull/54#issuecomment-2045438105
The defaults scenarios still have 'high' gen2 allocations but they are all owned by the TlsOverPerCoreLockedStacksArrayPool backing the System.Channels BoundedBuffer.
Unsure if there is anything we can do to control it.
See e.g this proposal to .NET https://github.com/dotnet/runtime/issues/53895
=> Update to latest ingest libraries

.github/workflows/release-main.yml, .github/workflows/release.yml
Run GitHub provenance and store the artifacts in GitHub.
=> github-action: add provenance

.github/workflows/release-main.yml, .github/workflows/release.yml
Top-level permissions are not honoured when job-level permissions are set. Hence, use read top-level permission and apply the job-level permissions that are required
=> github-action: fix permissions

ecs-dotnet.sln, src/Elastic.CommonSchema.NLog/EcsLayout.cs, src/Elastic.CommonSchema.NLog/Elastic.CommonSchema.NLog.csproj, src/Elastic.CommonSchema.NLog/README.md, src/Elastic.Extensions.Logging/ElasticsearchLoggerProvider.cs, src/Elastic.NLog.Targets/Elastic.NLog.Targets.csproj, src/Elastic.NLog.Targets/ElasticPoolType.cs, src/Elastic.NLog.Targets/ElasticsearchTarget.cs, src/Elastic.NLog.Targets/NodePoolType.cs, src/Elastic.NLog.Targets/README.md, tests-integration/Directory.Build.props, tests-integration/Elastic.NLog.Targets.IntegrationTests/Elastic.NLog.Targets.IntegrationTests.csproj, tests-integration/Elastic.NLog.Targets.IntegrationTests/LoggingCluster.cs, tests-integration/Elastic.NLog.Targets.IntegrationTests/LoggingToDataStreamTests.cs, tests-integration/Elastic.NLog.Targets.IntegrationTests/TestBase.cs, tests/Directory.Build.props
NLog Target that exports directly to Elastic Cloud or individual Elasticsearch nodes
Docs Preview: https://github.com/snakefoot/ecs-dotnet/tree/main/src/Elastic.NLog.Targets
=> NLog ElasticSearch Target

.github/workflows/release-main.yml, .github/workflows/release.yml
⚠️ This PR was created by an automated tool. Please review the changes carefully. ⚠️ 
NOTE: github-early-access/generate-build-provenance has been deprecated in favor of 
actions/attest-build-provenance.
If there are any questions, please reach out to the @elastic/observablt-ci
=> github-action: use actions/attest-build-provenance

.github/update-specs.yml, .github/workflows/update-specs.yml
Use oblt-actions with GitHub secrets.
No need to use Vault secrets path
=> ci: use updatecli with GitHub secrets

src/Elastic.CommonSchema.NLog/ActivityExtensions.cs, src/Elastic.CommonSchema.NLog/EcsLayout.cs, src/Elastic.CommonSchema.Serilog/EcsTextFormatterConfiguration.cs, src/Elastic.CommonSchema/EcsDocument.cs, src/Elastic.Extensions.Logging/Options/ElasticsearchLoggerOptions.cs
When enabling writing on background-thread, then one should not capture the activity-traceid of the background-thread.
I guess Serilog has the same issue, since it relies on its enricher-capture (similar to NLog layout capture)
This is ofcourse a breaking change, since adding new property to existing interface `IEcsDocumentCreationOptions`. Maybe change to use enum-flag-values?
Alternative only perform automatic capture for Elastic.Extensions.Logging? (Skip helping NLog / Serilog / Log4net)
=> Skip ActivityData capture for NLog, since doing Layout capture

src/Elastic.CommonSchema/Serialization/EcsDocumentJsonConverter.Generated.cs, src/Elastic.CommonSchema/Serialization/EcsDocumentJsonConverter.cs, src/Elastic.CommonSchema/Serialization/EcsJsonConverterBase.cs, src/Elastic.CommonSchema/Serialization/JsonConfiguration.cs, src/Elastic.CommonSchema/Serialization/PropertiesReaderJsonConverterBase.Generated.cs, src/Elastic.CommonSchema/Serialization/PropertiesReaderJsonConverterBase.cs, tests-integration/Elastic.Ingest.Elasticsearch.CommonSchema.IntegrationTests/CustomEventWriter.cs, tests-integration/Elastic.Ingest.Elasticsearch.CommonSchema.IntegrationTests/DataStreamIngestionTests.cs, tests-integration/Elastic.Ingest.Elasticsearch.CommonSchema.IntegrationTests/IndexIngestionTests.cs, tests-integration/Elastic.Ingest.Elasticsearch.CommonSchema.IntegrationTests/TestDocument.cs, tests/Elastic.CommonSchema.Tests/Serializes.cs, tools/Elastic.CommonSchema.Generator/Views/EcsDocumentJsonConverter.Generated.cshtml, tools/Elastic.CommonSchema.Generator/Views/PropertiesReaderJsonConverterBase.Generated.cshtml
This proposal enables users to supply their own event writers, while also honoring the serialization options they specify.
Furthermore, it introduces the capability to represent enums as strings, thereby enhancing flexibility and usability.
_Generated files have been updated by Elastic.CommonSchema.Generator project_
=> Add support for custom event writer

src/Elastic.CommonSchema/LogTemplateEntities.Generated.cs, src/Elastic.CommonSchema/PropDispatch.Generated.cs, src/Elastic.CommonSchema/PropDispatch.cs, tests/Elastic.CommonSchema.Serilog.Tests/EcsFieldsInTemplateTests.cs, tests/Elastic.CommonSchema.Serilog.Tests/Elastic.CommonSchema.Serilog.Tests.csproj, tests/Elastic.CommonSchema.Serilog.Tests/ExtensionsLogging/SerilogWithExtensionLoggerGenerated.cs, tools/Elastic.CommonSchema.Generator/FileGenerator.cs, tools/Elastic.CommonSchema.Generator/Views/LogTemplateEntities.Generated.cshtml, tools/Elastic.CommonSchema.Generator/Views/PropDispatch.Generated.cshtml
These will overwrite anything set by default by the integration so should be considered an expert level feature.
=> Allow ECS entities to be logged directly

.github/workflows/test-reporter.yml
This should fix https://github.com/elastic/ecs-dotnet/actions/runs/10830292993
=> Fix test-reporter permissions

src/Elastic.CommonSchema.NLog/EcsLayout.cs
Standard EcsDocument are pre-filled with different environment-specific details.
Allow NLog EcsLayout to make use of these details for Host + Service, and skip new allocation when previous value is identical.
=> NLog EcsLayout apply default service details like Environment

README.md, src/Elastic.CommonSchema.NLog/README.md, src/Elastic.NLog.Targets/README.md, src/Elastic.Serilog.Sinks/README.md
Preview of the updated frontpage README.md - https://github.com/snakefoot/ecs-dotnet/blob/main/README.md
=> Updated README.md with links to ingest nuget-packages for NLog and Serilog

src/Elastic.Ingest.Elasticsearch.CommonSchema/Elastic.Ingest.Elasticsearch.CommonSchema.csproj, src/Elastic.Serilog.Sinks/ElasticsearchSink.cs, tests-integration/Elasticsearch.IntegrationDefaults/Elasticsearch.IntegrationDefaults.csproj
This also updates our serology sink to implement `IDisposable` so it waits to flush as well. See also #411
=> Update to latest ingest that attempts to flush out buffer before fully disposing

ecs-dotnet.sln, src/Elastic.Serilog.Sinks/ConfigSinkExtensions.cs, src/Elastic.Serilog.Sinks/ElasticsearchSink.cs, src/Elastic.Serilog.Sinks/README.md, tests/Elastic.Serilog.Sinks.Tests/AppSettingsConfigTests.cs, tests/Elastic.Serilog.Sinks.Tests/ConfigurationBuilderExtensions.cs, tests/Elastic.Serilog.Sinks.Tests/Elastic.Serilog.Sinks.Tests.csproj, tests/Elastic.Serilog.Sinks.Tests/JsonConfigTestBase.cs, tests/Elastic.Serilog.Sinks.Tests/JsonStringConfigSource.cs, tests/Elastic.Serilog.Sinks.Tests/SimpleCases.cs
When configuring through `appsettings` only the `bootstrapMethod` configuration is **required**
```json5
{
"Serilog": {
"Using": [ "Elastic.Serilog.Sinks" ],
"MinimumLevel": { "Default": "Information" },
"WriteTo": [
{
"Name": "Elasticsearch",
"Args": {
"bootstrapMethod": "Silent",
"nodes": [ "http://elastichost:9200" ],
"useSniffing": true,
"apiKey": "<apiKey>",
"username": "<username>",
"password": "<password>",
"ilmPolicy" : "my-policy",
"dataStream" : "logs-dotnet-default",
"includeHost" : true,
"includeUser" : true,
"includeProcess" : true,
"includeActivity" : true,
"filterProperties" : [ "prop1", "prop2" ],
"proxy": "http://localhost:8200",
"proxyUsername": "x",
"proxyPassword": "y",
"debugMode": false,
//EXPERT settings, do not set unless you need to 
"maxRetries": 3, …
```
=> Add better support for Serilog.Settings.Configuration

.github/workflows/pre-commit.yml
⚠️ This PR was created by an automated tool. Please review the changes carefully. ⚠️ 
NOTE: https://github.com/elastic/apm-pipeline-library has been deprecated in favor of 
https://github.com/elastic/oblt-actions.
Requires https://github.com/elastic/oblt-actions/pull/119 to be merged.
If there are any questions, please reach out to the @elastic/observablt-ci
=> github-action: use oblt-actions/pre-commit

ecs-dotnet.sln, ecs-dotnet.sln.DotSettings, examples/Elastic.Extensions.Logging.Console.Example/Elastic.Extensions.Logging.Console.Example.csproj, examples/Elastic.Extensions.Logging.Console.Example/ExampleService.cs, examples/Elastic.Extensions.Logging.Console.Example/Program.cs, examples/Elastic.Extensions.Logging.Example/Elastic.Extensions.Logging.Example.csproj, src/Elastic.Extensions.Logging.Common/Elastic.Extensions.Logging.Common.csproj, src/Elastic.Extensions.Logging.Common/ILogEventCreationOptions.cs, src/Elastic.Extensions.Logging.Common/LogEvent.cs, src/Elastic.Extensions.Logging.Common/LogEventBuilderExtensions.cs, src/Elastic.Extensions.Logging.Common/LogEventToEcsHelper.cs, src/Elastic.Extensions.Logging.Common/README.md, src/Elastic.Extensions.Logging.Console/EcsConsoleFormatter.cs, src/Elastic.Extensions.Logging.Console/EcsConsoleFormatterOptions.cs, src/Elastic.Extensions.Logging.Console/Elastic.Extensions.Logging.Console.csproj, src/Elastic.Extensions.Logging.Console/LoggingBuilderExtensions.cs, src/Elastic.Extensions.Logging.Console/README.md, src/Elastic.Extensions.Logging/Elastic.Extensions.Logging.csproj, src/Elastic.Extensions.Logging/ElasticsearchLogger.cs, src/Elastic.Extensions.Logging/Options/ElasticsearchLoggerOptions.cs
- Introduce Console formatter Microsoft.Extensions.Logging
- Add README contents
=> Introduce Console formatter for Microsoft.Extensions.Logging.Console"

examples/aspnetcore-with-serilog/appsettings.Development.json, examples/aspnetcore-with-serilog/appsettings.json, src/Elastic.Extensions.Logging/ElasticsearchLoggerProvider.cs, src/Elastic.Ingest.Elasticsearch.CommonSchema/EcsDataStreamChannel.cs, src/Elastic.Ingest.Elasticsearch.CommonSchema/EcsIndexChannel.cs, src/Elastic.NLog.Targets/ElasticsearchTarget.cs, src/Elastic.Serilog.Enrichers.Web/Elastic.Serilog.Enrichers.Web.csproj, src/Elastic.Serilog.Enrichers.Web/HttpContextEnricher.cs
- Ensure correct embdedded logical name for UParser.regexes.cs
- Remove WriteEvent usages
=> Remove WriteEvent usages

examples/Elastic.Serilog.Sinks.Example/Elastic.Serilog.Sinks.Example.csproj, examples/aspnetcore-with-extensions-logging/aspnetcore-with-extensions-logging.csproj, examples/aspnetcore-with-serilog/AspnetCoreExample.csproj, src/Elastic.CommonSchema.BenchmarkDotNetExporter/ElasticsearchBenchmarkExporter.cs, src/Elastic.CommonSchema.BenchmarkDotNetExporter/ElasticsearchBenchmarkExporterOptions.cs, src/Elastic.Extensions.Logging/ElasticsearchLoggerProvider.cs, src/Elastic.Ingest.Elasticsearch.CommonSchema/Elastic.Ingest.Elasticsearch.CommonSchema.csproj, src/Elastic.NLog.Targets/ElasticsearchTarget.cs, src/Elastic.Serilog.Sinks/ConfigSinkExtensions.cs, src/Elastic.Serilog.Sinks/ElasticsearchSinkExtensions.cs, src/Elastic.Serilog.Sinks/TransportHelper.cs, tests-integration/Elastic.CommonSchema.BenchmarkDotNetExporter.IntegrationTests/BdNetExporterTests.cs, tests-integration/Elastic.Extensions.Logging.IntegrationTests/LoggingToDataStreamTests.cs, tests-integration/Elastic.Extensions.Logging.IntegrationTests/LoggingToIndexTests.cs, tests-integration/Elastic.Ingest.Elasticsearch.CommonSchema.IntegrationTests/DataStreamIngestionTests.cs, tests-integration/Elastic.NLog.Targets.IntegrationTests/LoggingToDataStreamTests.cs, tests-integration/Elastic.Serilog.Sinks.IntegrationTests/BootstrapMinimumSecurityPrivilegesTests.cs, tests-integration/Elastic.Serilog.Sinks.IntegrationTests/SerilogCluster.cs, tests-integration/Elastic.Serilog.Sinks.IntegrationTests/SerilogOutputTests.cs, tests-integration/Elastic.Serilog.Sinks.IntegrationTests/SerilogSelfLogTests.cs, tests-integration/Elasticsearch.IntegrationDefaults/Elasticsearch.IntegrationDefaults.csproj, tests-integration/Elasticsearch.IntegrationDefaults/IngestionCluster.cs, tests/Elastic.Serilog.Sinks.Tests/AppSettingsConfigTests.cs, tests/Elastic.Serilog.Sinks.Tests/JsonConfigTestBase.cs
- Updated Elastic.Clients.Elasticsearch
- Updated Elastic.Ingest.Elasticsearch
- Updated Microsoft.Extensions.Hosting in examples
Closes #463
=> Update Elastic packages to avoid transport failures

src/Elastic.CommonSchema.Serilog/LogEventConverter.cs
Extended LogEventConverter.ConvertToEcs<>() with an optional EcsDocumentCreationCache input parameter that gets passed into EcsDocument.CreateNewWithDefaults<>()
This is to support overwrites of static data such as those in EcsDocument.Service
=> Extended LogEventConverter.ConvertToEcs<>()

docs/reference/_formatters.md, docs/reference/extensions-logging-data-shipper.md, docs/reference/index.md, docs/reference/log4net-formatter.md, docs/reference/setup.md
Follow up to #481 
When using cross-repo links, the path should be relative to the `docset.yml` not the full path within the repo ([updated docs-builder docs](https://elastic.github.io/docs-builder/syntax/links/#cross-repository-links)).
=> [docs] Clean up cross-repo links

docs/reference/ecs-dotnet.md
This PR fixes a broken link in https://docs-v3-preview.elastic.dev/elastic/ecs-dotnet/tree/main/reference/ecs-dotnet.
=> [ECS reference docs] Fix broken link

docs/reference/serilog-data-shipper.md
Related to https://github.com/elastic/docs-content/pull/914
Removes reliance on temporary redirects in the docs-content repo.
=> [docs] Remove reliance on temporary redirects

src/Elastic.CommonSchema.NLog/EcsLayout.cs, src/Elastic.NLog.Targets/ElasticsearchTarget.cs
NLog v5 have marked the `ConfigurationItemFactory`-members as obsolete, and they will be removed with NLog v6 (to fix build-warnings about .NET trimming and AOT).
This PullRequest will allow the NLog EcsLayout to continue to work, when NLog v6 is released, and users are upgrading.
=> NLog EcsLayout stop using obsolete ConfigurationItemFactory members

src/Elastic.CommonSchema.Serilog/LogEventConverter.cs
(cherry picked from commit f973862b15ea1bac47a0e671600d87f73ca98e80)
=> Ensure we can handle more data types in ElapsedMillisecond/Elapsed from serilog (#514)

src/Elastic.Apm.NLog/ApmServiceNameLayoutRenderer.cs, src/Elastic.Apm.NLog/ApmServiceNodeNameLayoutRenderer.cs, src/Elastic.Apm.NLog/ApmServiceVersionLayoutRenderer.cs, src/Elastic.Apm.NLog/ApmSpanIdLayoutRenderer.cs, src/Elastic.Apm.NLog/ApmTraceIdLayoutRenderer.cs, src/Elastic.Apm.NLog/ApmTransactionIdLayoutRenderer.cs, src/Elastic.Apm.NLog/Elastic.Apm.NLog.csproj, src/Elastic.CommonSchema.NLog/EcsLayout.cs, src/Elastic.CommonSchema.NLog/Elastic.CommonSchema.NLog.csproj, src/Elastic.CommonSchema.NLog/README.md, tests/Elastic.Apm.NLog.Tests/Elastic.Apm.NLog.Tests.csproj, tests/Elastic.Apm.NLog.Tests/NLogTests.cs, tests/Elastic.CommonSchema.NLog.Tests/Elastic.CommonSchema.NLog.Tests.csproj, tests/Elastic.CommonSchema.NLog.Tests/LogTestsBase.cs, tests/Elastic.CommonSchema.NLog.Tests/MessageTests.cs, tests/Elastic.CommonSchema.NLog.Tests/WebTests.cs
Maybe the next major-version could also include NLog upgrade?
- NLog v5.2.5 released 15 Oct 2023
Also removed assignment of `HostIp = "${local-ip:cachedSeconds=60}`, since NLog v6 requires extra dependencies for network-stack.
=> NLog v5.2.5

src/Elastic.Ingest.Elasticsearch.CommonSchema/Elastic.Ingest.Elasticsearch.CommonSchema.csproj, src/Elastic.Serilog.Sinks/ElasticsearchSink.cs, tests-integration/Elasticsearch.IntegrationDefaults/Elasticsearch.IntegrationDefaults.csproj, tests/Elastic.Serilog.Sinks.Tests/Elastic.Serilog.Sinks.Tests.csproj, tests/Elastic.Serilog.Sinks.Tests/SerilogFailureOutputTests.cs
- Test fallback
- update
- Ensure fallback mechanism works with the latest ingest-dotnet
(cherry picked from commit a4c06a5fc31a3472d8b5caa4c1f71bec35bc83bc)
=> fix/test fallback serilog (#523)

examples/playground/Program.cs, src/Elastic.CommonSchema.BenchmarkDotNetExporter/ElasticsearchBenchmarkExporter.cs, src/Elastic.CommonSchema.NLog/EcsLayout.cs, src/Elastic.CommonSchema.NLog/NLogEcsJsonContext.cs, src/Elastic.CommonSchema.NLog/NlogEcsDocumentCreationOptions.cs, src/Elastic.CommonSchema/EcsDocument.Serialization.cs, src/Elastic.CommonSchema/Serialization/EcsJsonContext.Generated.cs, src/Elastic.CommonSchema/Serialization/JsonConfiguration.cs, src/Elastic.CommonSchema/Serialization/PropertiesReaderJsonConverterBase.cs, src/Elastic.Extensions.Logging.Common/LogEvent.cs, src/Elastic.Extensions.Logging.Common/LogEventJsonContext.cs, src/Elastic.Extensions.Logging/ElasticsearchLoggerOptionsSetup.cs, src/Elastic.Extensions.Logging/ElasticsearchLoggerProvider.cs, src/Elastic.Ingest.Elasticsearch.CommonSchema/Elastic.Ingest.Elasticsearch.CommonSchema.csproj, src/Elastic.NLog.Targets/ElasticsearchTarget.cs, src/Elastic.Serilog.Sinks/ElasticsearchSink.cs, tests-integration/Elastic.Ingest.Elasticsearch.CommonSchema.IntegrationTests/DataStreamIngestionTests.cs, tests-integration/Elastic.Ingest.Elasticsearch.CommonSchema.IntegrationTests/IndexIngestionTests.cs, tests-integration/Elasticsearch.IntegrationDefaults/Elasticsearch.IntegrationDefaults.csproj, tools/Elastic.CommonSchema.Generator/Views/EcsJsonContext.Generated.cshtml
- **Add EcsJsonContext.Default to JsonSerializerOptions**
- **Update JsonSerializerOptions to combine DefaultJsonTypeInfoResolver with EcsJsonContext**
- **Add JsonSerializable attributes for EcsDocument and Labels in EcsJsonContext**
=> Register TypeInfoProvider explicitly
