elastic/ecs-dotnet

src/Elastic.CommonSchema/Types.Generated.cs
src/Generator/FileGenerator.cs
src/Generator/Schema/NestedFields.cs
src/Generator/Schema/YamlSchema.cs

Improve XML documentation on Trace and Transaction objects.

---

src/Elastic.CommonSchema.Serilog/EcsTextFormatterConfiguration.cs
src/Elastic.CommonSchema.Serilog/LogEventConverter.cs

Ability to enrich the ECS from the log event
This is a breaking change but not sure if anyone was using this.
Fixes issue #20

Change mapping function to map data from the log event

---

README.md
src/Elastic.Apm.NLog/readme.md
src/Elastic.Apm.SerilogEnricher/readme.md
src/Elastic.CommonSchema.Serilog/README.md
src/Elastic.CommonSchema/README.md

Also link the project in the main readme

Introduce readme for Elastic.Apm.NLog

---

src/Elastic.CommonSchema.BenchmarkDotNetExporter/ElasticsearchBenchmarkExporter.cs

Fix NullReferenceEception if job is not specified in benchmark configuration.

---

src/Elastic.CommonSchema.Serilog/EcsTextFormatter.cs
src/Elastic.CommonSchema.Serilog/LogEventConverter.cs
tests/Elastic.CommonSchema.Serilog.Tests/MessageTests.cs

* fix EcsTextFormatter cannot support Dictionary properties
* add new line after LogEvent's json serialization

Fix Dictionary properties issue

---

src/Elastic.CommonSchema.Serilog/EcsTextFormatter.cs
src/Elastic.CommonSchema.Serilog/LogEventConverter.cs
tests/Elastic.CommonSchema.Serilog.Tests/MessageTests.cs

Adds support for Dictionary rendering.
Fixes newline issue in StreamWriter rendering.
Co-authored-by: kuanpak <kuanpak@gmail.com>

Adds formatting for additional Serilog objects

---

.ci/Jenkinsfile
build/scripts/Testing.fs
tests/Elastic.CommonSchema.BenchmarkDotNetExporter.IntegrationTests/BdNetExporterTests.cs

Enable the build and test in Windows.
There will be some other PRs to enable:
- test output visualization in the CI Pipeline.

ci(jenkins): add windows build stage

---

src/Elastic.Apm.NLog/ApmTraceIdLayoutRenderer.cs
src/Elastic.Apm.NLog/ApmTransactionIdLayoutRenderer.cs
src/Elastic.Apm.SerilogEnricher/ElasticApmEnricher.cs

Ensure calls to Agent.Tracer use null propagation to access child objects

---

src/Elasticsearch.Extensions.Logging/ElasticsearchLogger.cs
src/Elasticsearch.Extensions.Logging/ElasticsearchLoggerOptions.cs
src/Elasticsearch.Extensions.Logging/ElasticsearchLoggerProvider.cs

As per list of getting things ready for GA.
Removed unnecessary Cast<char>
Also cleaned up some other warnings/suggestions from Rider.

Extensions - remove cast<char>

---

src/Elastic.CommonSchema.NLog/EcsLayout.cs

Fix for https://github.com/elastic/ecs-dotnet/issues/123

Fix issue where wrong thread id was logged.

---

tests/Elastic.CommonSchema.Tests/Specs/spec.json

ECS logging specs automatic sync

synchronize ecs-logging spec

---

src/Elastic.CommonSchema.Serilog/EcsTextFormatter.cs

Write ECS formatted log event to TextWriter

---

ecs-dotnet.sln
src/Directory.Build.props

This commit fixes the package urls to point at the correct repository.

Fix package urls

---

src/Elastic.Ingest/Elastic.Ingest.csproj

Still waiting on some improvements from #110 to come through before this should go live on NuGet.

Revert shipping Elastic.Ingest

---

src/Elastic.CommonSchema/Serialization/JsonConfiguration.cs

Allow to add a custom json converter.
#168

Public SerializerOptions

---

src/Elastic.CommonSchema.Generator/FileGenerator.cs
src/Elastic.CommonSchema.Generator/Views/EcsDocumentJsonConverter.Generated.cshtml
src/Elastic.CommonSchema.Generator/Views/EcsJsonContext.Generated.cshtml
src/Elastic.CommonSchema/EcsDocumentJsonConverter.Generated.cs
src/Elastic.CommonSchema/EcsJsonContext.Generated.cs
src/Elastic.CommonSchema/Serialization/EcsJsonConverterBase.cs
tests/Elastic.CommonSchema.Benchmarks/Elastic.CommonSchema.Benchmarks.csproj
tests/Elastic.CommonSchema.Benchmarks/Program.cs
tests/Elastic.CommonSchema.Benchmarks/SerializingBase.cs
tests/Elastic.CommonSchema.Benchmarks/SerializingStringBuilderBase.cs
tests/Elastic.CommonSchema.Serilog.Tests/Repro/GithubIssue31.cs

This adds significant performance boost locally compare previous (`main`) especially for larger `EcsDocument` instances. 
|     Method |         Mean |       Error |      StdDev | Completed Work Items | Lock Contentions |   Gen 0 |   Gen 1 |   Gen 2 | Allocated |
|----------- |-------------:|------------:|------------:|---------------------:|-----------------:|--------:|--------:|--------:|----------:|
|      Empty |     571.0 ns |    11.43 ns |    12.23 ns |                    - |                - |  0.0916 |       - |       - |     768 B |
|    Minimal |   1,051.2 ns |    16.64 ns |    13.90 ns |                    - |                - |  0.1163 |       - |       - |     984 B |
|    Complex |   2,309.7 ns |    39.75 ns |    40.82 ns |                    - |                - |  0.2365 | …

Implements System.Text.Json Source Generators

---

src/Elastic.CommonSchema.Serilog/LogEventConverter.cs

Caches up to 10k Process instances. The current process is cached
seperately.

Fix #224 cache process lookup in serilog formatter.

---

examples/aspnetcore-with-serilog/AspnetCoreExample.csproj
examples/aspnetcore-with-serilog/Program.cs
src/Elastic.CommonSchema.Serilog/EcsTextFormatterConfiguration.cs
src/Elastic.CommonSchema.Serilog/EnricherExtensions.cs
src/Elastic.CommonSchema.Serilog/Http/HttpContextAccessorAdapter.cs
src/Elastic.CommonSchema.Serilog/Http/HttpContextAdapter.cs
src/Elastic.CommonSchema.Serilog/Http/HttpContextEnricher.cs
src/Elastic.CommonSchema.Serilog/Http/IHttpAdapter.cs
src/Elastic.CommonSchema.Serilog/LogEventConverter.cs
src/Elastic.CommonSchema.Serilog/README.md
src/Elastic.CommonSchema.Serilog/SpecialKeys.cs

Fixes #186
(cherry picked from commit d26b026e72dbc4436d91c6a9ef9532176772d494)

Ensure we set HttpContext through enrichers synchronously

---

ecs-dotnet.sln
examples/aspnetcore-with-extensions-logging/Controllers/WeatherForecastController.cs
examples/aspnetcore-with-extensions-logging/Program.cs
examples/aspnetcore-with-extensions-logging/WeatherForecast.cs
examples/aspnetcore-with-extensions-logging/appsettings.Development.json
examples/aspnetcore-with-extensions-logging/appsettings.json
examples/aspnetcore-with-extensions-logging/aspnetcore-with-extensions-logging.csproj
src/Elasticsearch.Extensions.Logging/ElasticsearchLogger.cs
src/Elasticsearch.Extensions.Logging/ElasticsearchLoggerProvider.cs
src/Elasticsearch.Extensions.Logging/LoggingBuilderExtensions.cs
src/Elasticsearch.Extensions.Logging/Options/ElasticsearchLoggerOptions.cs

Projects known labels to http.* and url.* now.
Improves how Scopes.* are resolved.

Improves on Elasticsearch.Extensions.Logging and ASP.NET

---

src/Elastic.CommonSchema.BenchmarkDotNetExporter/ElasticsearchBenchmarkExporter.cs
src/Elastic.Ingest.Elasticsearch.CommonSchema/Elastic.Ingest.Elasticsearch.CommonSchema.csproj
tests-integration/Elasticsearch.IntegrationDefaults/Elasticsearch.IntegrationDefaults.csproj

https://github.com/elastic/elastic-ingest-dotnet/releases/tag/0.3.1

Update to latest Elastic.Ingest.* that ships with debug symbols and xml docs

---

src/Elastic.CommonSchema/Serialization/EcsJsonConverterBase.cs
src/Elastic.Ingest.Elasticsearch.CommonSchema/Elastic.Ingest.Elasticsearch.CommonSchema.csproj
tests-integration/Elasticsearch.IntegrationDefaults/Elasticsearch.IntegrationDefaults.csproj

This version no longer copies arrarys and uses ArrayPool.

Bump Elastic.Ingest to 0.5

---

src/Elastic.Ingest.Elasticsearch.CommonSchema/Elastic.Ingest.Elasticsearch.CommonSchema.csproj
tests-integration/Elasticsearch.IntegrationDefaults/Elasticsearch.IntegrationDefaults.csproj

Bump to latest Elastic.Ingest.* & Elastic.Transport.*

---

src/Elastic.Ingest.Elasticsearch.CommonSchema/Elastic.Ingest.Elasticsearch.CommonSchema.csproj
tests-integration/Elasticsearch.IntegrationDefaults/Elasticsearch.IntegrationDefaults.csproj

These now include better exception messages

Update to latest Elastic.Ingest.*

---

docs/data-shippers/index.asciidoc
src/Elastic.CommonSchema.BenchmarkDotNetExporter/ElasticsearchBenchmarkExporterOptions.cs
src/Elastic.Extensions.Logging/ElasticsearchLoggerProvider.cs
src/Elastic.Ingest.Elasticsearch.CommonSchema/Elastic.Ingest.Elasticsearch.CommonSchema.csproj
src/Elastic.Serilog.Sinks/TransportHelper.cs
tests-integration/Elastic.Serilog.Sinks.IntegrationTests/BootstrapMinimumSecurityPrivilegesTests.cs
tests-integration/Elastic.Serilog.Sinks.IntegrationTests/SerilogCluster.cs
tests-integration/Elasticsearch.IntegrationDefaults/Elasticsearch.IntegrationDefaults.csproj
tests-integration/Elasticsearch.IntegrationDefaults/IngestionCluster.cs

- Document minimum privileges required if Security is enabled
- add docs
- add tests

Document minimum privileges

---

src/Elastic.Extensions.Logging/ElasticsearchLoggerProvider.cs
src/Elastic.Extensions.Logging/Options/ElasticsearchLoggerOptions.cs
src/Elastic.Serilog.Sinks/ElasticsearchSink.cs

Expose IlmPolicy as option to datashippers

---

tools/Elastic.CommonSchema.Generator/CodeConfiguration.cs
tools/Elastic.CommonSchema.Generator/Elastic.CommonSchema.Generator.csproj
tools/Elastic.CommonSchema.Generator/Program.cs
tools/Elastic.CommonSchema.Generator/SpecificationDownloader.cs

Prompted because our html scanning broke due to github switching to turbopages and so we never saw directory listings in the inititial html.

Move to OctoKit and support access tokens and include wait for ratelimits

---

.github/update-specs.yml
.github/workflows/update-specs.yml

Use signed commits:
- https://github.com/updatecli/updatecli/issues/1914

ci: updatecli signed commits

---

src/Elastic.CommonSchema.NLog/EcsLayout.cs
src/Elastic.CommonSchema.Serilog/EcsTextFormatterConfiguration.cs
src/Elastic.CommonSchema/EcsDocument.cs
src/Elastic.Extensions.Logging/Options/ElasticsearchLoggerOptions.cs

Rename IncludeTraceId to IncludeActivityData

---

.github/workflows/bootstrap/action.yml

⚠️ This PR was created by an automated tool. Please review the changes carefully. ⚠️ 
NOTE: https://github.com/elastic/apm-pipeline-library has been deprecated in favor of 
https://github.com/elastic/oblt-actions.
If there are any questions, please reach out to the @elastic/observablt-ci

github-action: use oblt-actions/git/setup

---

examples/Elastic.Extensions.Logging.Console.Example/Elastic.Extensions.Logging.Console.Example.csproj
examples/Elastic.Extensions.Logging.Console.Example/Program.cs
src/Elastic.Extensions.Logging.Common/ILogEventCreationOptions.cs
src/Elastic.Extensions.Logging.Console/EcsConsoleFormatter.cs
src/Elastic.Extensions.Logging.Console/EcsConsoleFormatterOptions.cs
src/Elastic.Extensions.Logging.Console/LoggingBuilderExtensions.cs
src/Elastic.Extensions.Logging/ElasticsearchLogger.cs
src/Elastic.Extensions.Logging/Options/ElasticsearchLoggerOptions.cs

This existed for Serilog but not Extensions Logging.

Add MapCustom to Extensions logging

---

src/Elastic.Extensions.Logging/ElasticsearchLoggerProvider.cs
src/Elastic.Extensions.Logging/Options/ElasticsearchLoggerOptions.cs
src/Elastic.NLog.Targets/ElasticsearchTarget.cs
src/Elastic.NLog.Targets/README.md

Elastic.NLog.Targets - Added support for CertificateFingerprint and ProxyUrl

---

src/Elastic.NLog.Targets/ElasticsearchTarget.cs

Checking the return-code of `_channel.TryWrite(...)`

Elastic.NLog.Targets - Report when Elastic Channel Buffer is full

---

src/Elastic.Ingest.Elasticsearch.CommonSchema/Elastic.Ingest.Elasticsearch.CommonSchema.csproj
tests-integration/Elasticsearch.IntegrationDefaults/Elasticsearch.IntegrationDefaults.csproj

(cherry picked from commit 5df00aa006c26e41045fa40594358ff9c52da833)

Ensure we reference an up to date Elastic.Ingest.Elasticsearch (#520)
